import java.util.Scanner;

abstract class Form {
    public abstract void collectDetails();
    public abstract void displayDetails();
}


class Feedback {
   
    private String studentName;
    private String classGrade;
    private String teacherName;
    private String subject;

    private int overallRating;
    private int punctualityRating;
    private int knowledgeRating;
    private int methodologyRating;
    private int clarityRating;
    private int engagementRating;
    private int feedbackRating;
    private int availabilityRating;
    private int classroomManagementRating;
    private int motivationalRating;
    private int respectfulnessRating;

    private String comments;

    public String getStudentName() { return studentName; }
    public void setStudentName(String studentName) { this.studentName = studentName; }

    public String getClassGrade() { return classGrade; }
    public void setClassGrade(String classGrade) { this.classGrade = classGrade; }

    public String getTeacherName() { return teacherName; }
    public void setTeacherName(String teacherName) { this.teacherName = teacherName; }

    public String getSubject() { return subject; }
    public void setSubject(String subject) { this.subject = subject; }

    public int getOverallRating() { return overallRating; }
    public void setOverallRating(int overallRating) { this.overallRating = overallRating; }

    public int getPunctualityRating() { return punctualityRating; }
    public void setPunctualityRating(int punctualityRating) { this.punctualityRating = punctualityRating; }

    public int getKnowledgeRating() { return knowledgeRating; }
    public void setKnowledgeRating(int knowledgeRating) { this.knowledgeRating = knowledgeRating; }

    public int getMethodologyRating() { return methodologyRating; }
    public void setMethodologyRating(int methodologyRating) { this.methodologyRating = methodologyRating; }

    public int getClarityRating() { return clarityRating; }
    public void setClarityRating(int clarityRating) { this.clarityRating = clarityRating; }

    public int getEngagementRating() { return engagementRating; }
    public void setEngagementRating(int engagementRating) { this.engagementRating = engagementRating; }

    public int getFeedbackRating() { return feedbackRating; }
    public void setFeedbackRating(int feedbackRating) { this.feedbackRating = feedbackRating; }

    public int getAvailabilityRating() { return availabilityRating; }
    public void setAvailabilityRating(int availabilityRating) { this.availabilityRating = availabilityRating; }

    public int getClassroomManagementRating() { return classroomManagementRating; }
    public void setClassroomManagementRating(int classroomManagementRating) { this.classroomManagementRating = classroomManagementRating; }

    public int getMotivationalRating() { return motivationalRating; }
    public void setMotivationalRating(int motivationalRating) { this.motivationalRating = motivationalRating; }

    public int getRespectfulnessRating() { return respectfulnessRating; }
    public void setRespectfulnessRating(int respectfulnessRating) { this.respectfulnessRating = respectfulnessRating; }

    public String getComments() { return comments; }
    public void setComments(String comments) { this.comments = comments; }
}


class FeedbackForm extends Form {
    private Feedback feedback;

    public FeedbackForm() {
        this.feedback = new Feedback();
    }


    public void collectDetails() {
        Scanner scanner = new Scanner(System.in);

        System.out.println("===== Teacher's Feedback Form =====");
        System.out.print("Enter Student's Your Name: ");
        feedback.setStudentName(scanner.nextLine());

        System.out.print("Enter Your Department: ");
        feedback.setClassGrade(scanner.nextLine());

        System.out.print("Enter Teacher's Name: ");
        feedback.setTeacherName(scanner.nextLine());

        System.out.print("Enter Subject: ");
        feedback.setSubject(scanner.nextLine());

        feedback.setOverallRating(collectRating(scanner, "Rate the teacher overall out of 5: "));
        feedback.setPunctualityRating(collectRating(scanner, "Knowledge base of the teacher(as perceived by you): "));
        feedback.setKnowledgeRating(collectRating(scanner, "Communication Skills of the teacher(in terms of course delivery and making you understand the course): "));
        feedback.setMethodologyRating(collectRating(scanner, "Sincerity / Commitment of the teacher: "));
        feedback.setClarityRating(collectRating(scanner, "Interest generated by the teacher: "));
        feedback.setEngagementRating(collectRating(scanner, "Ability to integrate course material with environment/Other issues, to provide a broader perspective: "));
        feedback.setFeedbackRating(collectRating(scanner, "Ability to integrate content with other courses: "));
        feedback.setAvailabilityRating(collectRating(scanner, "Accessibility of the teacher in and out of the class (Includes availability of the teacher to motivate further study and discussion outside class): "));
        feedback.setClassroomManagementRating(collectRating(scanner, "Ability of the teacher to design Tests/Quiz/assignments/examinations and projects to evaluate your understanding of the course: "));
        feedback.setMotivationalRating(collectRating(scanner, "Provision of sufficient time for you to give feedback during the course : "));
        feedback.setRespectfulnessRating(collectRating(scanner, "Overall rating: "));
       

        System.out.print("Enter your comments (optional): ");
        feedback.setComments(scanner.nextLine());

        System.out.println("Thank you for your feedback!");
    }

    private int collectRating(Scanner scanner, String prompt) {
        int rating;
        do {
            System.out.print(prompt);
            rating = scanner.nextInt();
            if (rating < 1 || rating > 5) {
                System.out.println("Invalid rating! Please enter a number between 1 and 5.");
            }
        } while (rating < 1 || rating > 5);
        scanner.nextLine();  
        return rating;
    }
    public void displayDetails() {
        System.out.println("\n===== Feedback Summary =====");
        System.out.println("Student: " + feedback.getStudentName());
        System.out.println("Class/Grade: " + feedback.getClassGrade());
        System.out.println("Teacher: " + feedback.getTeacherName());
        System.out.println("Subject: " + feedback.getSubject());
        System.out.println("Overall Rating: " + feedback.getOverallRating() + "/5");
        System.out.println("Punctuality Rating: " + feedback.getPunctualityRating() + "/5");
        System.out.println("Knowledge Rating: " + feedback.getKnowledgeRating() + "/5");
        System.out.println("Methodology Rating: " + feedback.getMethodologyRating() + "/5");
        System.out.println("Clarity in Communication: " + feedback.getClarityRating() + "/5");
        System.out.println("Engagement Level: " + feedback.getEngagementRating() + "/5");
        System.out.println("Feedback on Assignments: " + feedback.getFeedbackRating() + "/5");
        System.out.println("Availability for Help: " + feedback.getAvailabilityRating() + "/5");
        System.out.println("Classroom Management: " + feedback.getClassroomManagementRating() + "/5");
        System.out.println("Motivational Ability: " + feedback.getMotivationalRating() + "/5");
        System.out.println("Respectfulness: " + feedback.getRespectfulnessRating() + "/5");
        System.out.println("Comments: " + feedback.getComments());
    }
}
public class Main {
    public static void main(String[] args) {
        FeedbackForm form = new FeedbackForm();
        form.collectDetails();
        form.displayDetails();
    }
}